### ISSUE TITLE
Unknown function DirOnDirectory

### ISSUE THREAD

**Issue by LemonBoy** [habamax/vim-dir#18]
The problem appears whenever `exists(":Explore")` is false, that is when NetRW is not loaded.

It seems that Vim cannot find the local and unexported function `DirOnDirectory`, that makes sense if the autocommand is executed in a new scope with no relationship to the parent one where the function is defined.

I believe adding a `s:` prefix should do the trick.

**Comment by habamax** [comment]
Thx, could you try the fix?
