### ISSUE TITLE
Do not change working directory

### ISSUE THREAD

**Issue by lmoellendorf** [habamax/vim-dir#20]
I am using vim as IDE. I have some customization which depend  on working directory being the top level directory  of my project. All files should be opened relative to this top level project directory.

However, if I use `Dir` to select a file the working directory is changed to the directory containing the file.

For my setup it is necessary that the working directory is not changed, but the file is opened relative to the initial working directory.

Is it possible to change `vim-dir`'s behavior accordingly?

**Comment by habamax** [comment]
I don't remember why it changes working directory to be honest.

Please check latest version and let me know if there would be issues.

PS, I have my own project root auto change so I even didn't notice it.

**Comment by habamax** [comment]
> I don't remember why it changes working directory to be honest.

Well I've got some "bugs" so now I remember why I did it.

Now it should work, but there might be bugs.

PS, now I need to think how to edit a file in current dir, `:e newfilename` wouldn't work apparently.

**Comment by habamax** [comment]
`cc` would be `create a file in current directory`

Closing for now, let me know if you encounter bugs.
